### ISSUE TITLE
IKVM .net core on Linux

### ISSUE THREAD

**Issue by vin2890** [ams-tschoening/ikvm-bin#1]
Anyway we can get this ported over to linux?

**Comment by ams-tschoening** [comment]
This repo is only used as mostly internal storage for available releases, so there won't be anything to be ported in the strict sense. You should discuss your suggestion where the source is instead:

https://github.com/ikvm-revived/ikvm

I suggest to provide more details in the newly to create issue about your use case, what exactly you want to run how on Linux and stuff like that. There's ongoing work to port things to .NET Core already into which you might want to get involved.

https://docs.microsoft.com/en-us/dotnet/core/install/linux
https://github.com/ikvm-revived/ikvm/pull/25
https://github.com/ikvm-revived/ikvm/issues/20
https://github.com/ikvm-revived/ikvm/issues/21

You might want to give the available files a try using WINE or something like that as well, simply depends on what your actual use case is.

https://www.winehq.org

**Comment by vin2890** [comment]
We need KeepAlive Implemented for Linux to use Kerberos via IKVM we would potentially need to change => 
Class = TwoStacksPlainDatagramSocketImpl

socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.KeepAlive, true);

socket.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.TcpKeepAliveInterval, 5); 


This is the error we are getting without that method change

No Title
The error:
System.PlatformNotSupportedException: Socket.IOControl handles Windows-specific control codes and is not supported on this platform.
   at System.Net.Sockets.SocketPal.WindowsIoctl(SafeSocketHandle handle, Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue, Int32& optionLength)
   at System.Net.Sockets.Socket.IOControl(Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
   at ikvm.internal.Winsock.WSAIoctl(Socket , Int32 , Byte[] , Byte[] )
   at ikvm.internal.Winsock.WSAIoctl(Socket , Int32 , Boolean )
   at java.net.TwoStacksPlainDatagramSocketImpl_c.connect0(JNI$JNIEnv , TwoStacksPlainDatagramSocketImpl , InetAddress , Int32 )
   at java.net.TwoStacksPlainDatagramSocketImpl.connect0(InetAddress , Int32 )
   at java.net.AbstractPlainDatagramSocketImpl.connect(InetAddress , Int32 )
   at java.net.DatagramSocket.connectInternal(InetAddress , Int32 )
   at java.net.DatagramSocket.connect(InetAddress address, Int32 port)
   at com.sun.jndi.dns.DnsClient.doUdpQuery(Packet , InetAddress , Int32 , Int32 , Int32 )
   at com.sun.jndi.dns.DnsClient.query(DnsName , Int32 , Int32 , Boolean , Boolean )
   at com.sun.jndi.dns.Resolver.query(DnsName , Int32 , Int32 , Boolean , Boolean )
   at com.sun.jndi.dns.DnsContext.c_getAttributes(Name name, String[] attrIds, Continuation cont)
   at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_getAttributes(Name name, String[] attrIds, Continuation cont)
   at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(Name name, String[] attrIds)
   at com.sun.jndi.toolkit.url.GenericURLDirContext.getAttributes(String name, String[] attrIds)
   at sun.security.krb5.KrbServiceLocator.getKerberosService(String , String )
   at sun.security.krb5.Config.getKDCFromDNS(String )
   at sun.security.krb5.Config.getKDCList(String realm)
   at sun.security.krb5.KdcComm.send(Byte[] , Boolean )
   at sun.security.krb5.KdcComm.send(Byte[] obuf)
   at sun.security.krb5.KrbAsReqBuilder.send()
   at sun.security.krb5.KrbAsReqBuilder.action()
   at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Boolean )
   at com.sun.security.auth.module.Krb5LoginModule.login()
